### ISSUE TITLE
접속하는데 3개의 사이트를 접속해야 하는것이 불편합니다.

### ISSUE THREAD

**Issue by Taemean** [sumannam/online-vm-platform#12]
![image](https://user-images.githubusercontent.com/71322439/98887226-eea10d00-24d8-11eb-9309-a58e620a045a.png)
온라인 실습체계에 접속하기 위해서는 위 사진 처럼 총 3가지의 사이트를 열어야 접속이 가능합니다.
사용자가 이용하는데 한 가지의 사이트 주소도 기억하기 어려운데, 세 가지의 주소를 기억하는데 어려움이 있습니다.

**Comment by sumannam** [comment]
#3 과 동일한 이슈임
