### ISSUE TITLE
해상도 문제 개선요청

### ISSUE THREAD

**Issue by DaEun2020** [sumannam/online-vm-platform#2]
온라인 실습체계를 써보고나서 불편한점을 개선했으면 좋겠다.
사용자 입장에서 해상도가 낮아서 글자를 볼때 알아보기 힘들고 불편하다는 것이다.
해상도를 높여서 사용자입장에서 더 보기 편했으면 좋겠다.
온라인실습체계->로그인->실습하기-> 실습체계 화면 로그인-> 이클립스
![image](https://user-images.githubusercontent.com/71476200/98886134-c7494080-24d6-11eb-93b5-0ca2f3135292.png)
정다은_2019271062

**Comment by sangwoon0824** [comment]
실습체계 접속 후 바탕화면 오른쪽 클릭 -> 디스플레이 설정으로 해상도 변경 가능합니다

**Comment by kmr5259** [comment]
실습체계 접속 후 ctrl + 드래그로 확대가 가능하며 F11키로 전체화면 모드 활성화가 가능합니다.
